// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuOnA-oARpmyJC3iuhNkohG-dP7RHLlfk',
    appId: '1:787564299795:web:5bbbe3b8fb261e8c2ae1e6',
    messagingSenderId: '787564299795',
    projectId: 'shiftappens-2024',
    authDomain: 'shiftappens-2024.firebaseapp.com',
    storageBucket: 'shiftappens-2024.appspot.com',
    measurementId: 'G-KJ4QVEHE8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHYroqSZHWfJdAjEed3Ksgx5oD3G_3S8g',
    appId: '1:787564299795:android:4076489526ea4d772ae1e6',
    messagingSenderId: '787564299795',
    projectId: 'shiftappens-2024',
    storageBucket: 'shiftappens-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRrzKdDqJs7OhVC09XZ5tH37PTJtvKTCY',
    appId: '1:787564299795:ios:1dde7816d562804f2ae1e6',
    messagingSenderId: '787564299795',
    projectId: 'shiftappens-2024',
    storageBucket: 'shiftappens-2024.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRrzKdDqJs7OhVC09XZ5tH37PTJtvKTCY',
    appId: '1:787564299795:ios:1dde7816d562804f2ae1e6',
    messagingSenderId: '787564299795',
    projectId: 'shiftappens-2024',
    storageBucket: 'shiftappens-2024.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuOnA-oARpmyJC3iuhNkohG-dP7RHLlfk',
    appId: '1:787564299795:web:8cf665722fffaa012ae1e6',
    messagingSenderId: '787564299795',
    projectId: 'shiftappens-2024',
    authDomain: 'shiftappens-2024.firebaseapp.com',
    storageBucket: 'shiftappens-2024.appspot.com',
    measurementId: 'G-PFDKLCNCGF',
  );
}
